import * as Yup from 'yup';


export const employeeSchema= Yup.object().shape({
    id: Yup.number().integer(),
    enable: Yup.boolean(),
    series: Yup.string(),
    gender: Yup.string().required('Gender is required'),
    firstName: Yup.string().required('First Name is required'),
    lastName: Yup.string(),
    fullName: Yup.string(),
    middleName: Yup.string(),
    dateOfJoining: Yup.date().required('Date of Joining is required'),
    dateofbirth: Yup.date().required('Date of Birth is required'),
    status: Yup.string().required('Status is required'),
    salutation: Yup.string(),
    companyId: Yup.number().integer(),
    employeeAttendanceLeavesId: Yup.number().integer(),
    employeeAttendanceLeaves: Yup.object().shape({
      id: Yup.number().integer(),
      enable: Yup.boolean(),
      attendanceDeviceID: Yup.string(),
      holidayListId: Yup.number().integer(),
     
      shiftTypeId: Yup.number().integer(),
      
      expenseApproverId: Yup.number().integer(),
      shiftRequestApproverId: Yup.number().integer(),
      leaveApproverId: Yup.number().integer(),
    }),
    designationId: Yup.number().integer(),
    branchId: Yup.number().integer(),
    employeeGradeId: Yup.number().integer(),
    employmentTypeId: Yup.number().integer(),
    reportsTo: Yup.string(),
    employeeAddressId: Yup.number().integer(),
    employeeAddress: Yup.object().shape({
      id: Yup.number().integer(),
      enable: Yup.boolean(),
      mobile: Yup.string(),
      personalEmail: Yup.string().email('Invalid email address'),
      companyName: Yup.string(),
      preferedContactEmail: Yup.string(),
      currentAddress: Yup.string(),
      currentAddressIs: Yup.string(),
      permanentAddress: Yup.string(),
      permanentAddressIs: Yup.string(),
      emergencyContactName: Yup.string(),
      emergencyPhone: Yup.string(),
      relation: Yup.string(),
    }),
    employeeJoiningId: Yup.number().integer(),
    employeeJoiningDetails: Yup.object().shape({
      id: Yup.number().integer(),
      enable: Yup.boolean(),
      jobApplicantId: Yup.number().integer(),
      confirmationDate: Yup.date(),
      noticeDays: Yup.number().integer(),
      offerDate: Yup.date(),
      contractEndDate: Yup.date(),
      dateOfRetirement: Yup.date(),
    }),
    employeeSalaryId: Yup.number().integer(),
    employeeSalary: Yup.object().shape({
      id: Yup.number().integer(),
      enable: Yup.boolean(),
      ctc: Yup.number(),
      costCenterId: Yup.number().integer(),
      salaryCurrency: Yup.string(),
      panNumber: Yup.string(),
      salaryMode: Yup.string(),
      providentFundAccount: Yup.string(),
    }),
    personalId: Yup.number().integer(),
    personal: Yup.object().shape({
      id: Yup.number().integer(),
      enable: Yup.boolean(),
      maritalStatus: Yup.string(),
      bloodGroup: Yup.string(),
      familyBackground: Yup.string(),
      healthDetails: Yup.string(),
      healthInsuranceProvider: Yup.string(),
      passportNumber: Yup.string(),
      placeofIssue: Yup.string(),
      dateofIssue: Yup.date(),
      validUpto: Yup.date(),
    }),
    profileId: Yup.number().integer(),
    profile: Yup.object().shape({
      id: Yup.number().integer(),
      enable: Yup.boolean(),
      bioCoverLetter: Yup.string(),
      educationalQualificationId: Yup.number().integer(),
      educationalQualification: Yup.object().shape({
        id: Yup.number().integer(),
        enable: Yup.boolean(),
        school: Yup.string(),
        qualification: Yup.string(),
        level: Yup.string(),
        yearOfPassing: Yup.number().integer(),
        percentage: Yup.number(),
        majorSubjects: Yup.string(),
        employeeId: Yup.number().integer(),
        employee: Yup.string(),
      }),
      previousWorkExperienceId: Yup.number().integer(),
      previousWorkExperience: Yup.object().shape({
        id: Yup.number().integer(),
        enable: Yup.boolean(),
        company: Yup.string(),
        designation: Yup.string(),
        salary: Yup.number(),
        address: Yup.string(),
        contact: Yup.string(),
        totalExperience: Yup.number().integer(),
        employeeId: Yup.number().integer(),
        employee: Yup.string(),
      }),
      employeeHistoryId: Yup.number().integer(),
      employeeHistory: Yup.object().shape({
        id: Yup.number().integer(),
        enable: Yup.boolean(),
        designationId: Yup.number().integer(),
        departmentId: Yup.number().integer(),
        branchId: Yup.number().integer(),
        fromDate: Yup.date(),
        toDate: Yup.date(),
        employeeId: Yup.number().integer(),
        employee: Yup.string(),
      }),
    }),
    exitId: Yup.number().integer(),
    exit: Yup.object().shape({
      id: Yup.number().integer(),
      enable: Yup.boolean(),
      resignationLetterDate: Yup.date(),
      exitInterviewHeldOn: Yup.date(),
      leaveEncashed: Yup.boolean(),
      relievingDate: Yup.date(),
      newWorkPlace: Yup.string(),
      reasonforLeaving: Yup.string(),
      feedback: Yup.string(),
    }),
    educationalQualifications: Yup.array().of(
      Yup.object().shape({
        id: Yup.number().integer(),
        enable: Yup.boolean(),
        school: Yup.string(),
        qualification: Yup.string(),
        level: Yup.string(),
        yearOfPassing: Yup.number().integer(),
        percentage: Yup.number(),
        majorSubjects: Yup.string(),
        employeeId: Yup.number().integer(),
        employee: Yup.string(),
      })
    ),
    previousWorkExperiences: Yup.array().of(
      Yup.object().shape({
        id: Yup.number().integer(),
        enable: Yup.boolean(),
        company: Yup.string(),
        designation: Yup.string(),
        salary: Yup.number(),
        address: Yup.string(),
        contact: Yup.string(),
        totalExperience: Yup.number().integer(),
        employeeId: Yup.number().integer(),
        employee: Yup.string(),
      })
    ),
    employeeHistories: Yup.array().of(
      Yup.object().shape({
        id: Yup.number().integer(),
        enable: Yup.boolean(),
        designationId: Yup.number().integer(),
        departmentId: Yup.number().integer(),
        branchId: Yup.number().integer(),
        fromDate: Yup.date(),
        toDate: Yup.date(),
        employeeId: Yup.number().integer(),
        employee: Yup.string(),
      })
    ),
  });
  
  