export const employeeOptions = [
    {value:'',label:''},
    { value: '1-10', label: '1-10' },
    { value: '11-50', label: '11-50' },
    { value: '51-200', label: '51-200' },
    { value: '201-500', label: '201-500' },
    { value: '501-1000', label: '501-1000' },
    { value: '1000+', label: '1000+' }
];
export const designtions = [
    { value: '', label: '' },
    { value: 'CEO/Founder/GM', label: 'CEO/Founder/GM' },
    { value: 'CFO', label: 'CFO' },
    { value: 'CTO/CIO', label: 'CTO/CIO' },
    { value: 'Vice president', label: 'Vice president' },
    { value: 'Director/Head of Department', label: 'Director/Head of Department' },
    { value: 'IT/System manager', label: 'IT/System manager' },
    { value: 'Manager (Sales/Marketing/Customer)', label: 'Manager (Sales/Marketing/Customer)' },
    { value: 'Developer/Analyst', label: 'Developer/Analyst' },
    { value: 'Student/Freelancer/Just looking', label: 'Student/Freelancer/Just looking' },
    { value: 'Others', label: 'Others' }
];

export const BASEURL="https://localhost:7038/api/";

export const inputs = [
    { label: "Phone Number", name : "phoneNumber" },
    { label: "Financial Year Begins On", type: "date" , name : "financialYearBeginsOn"}
];

export const INDUSTRY = [
    {label : ''},
    {label : 'Distribution'},
    {label : 'Manufacturing'},
    {label : 'Retail'},
    {label : 'Education'},
    {label : 'Services'},
    {label : 'Agriculture'},
    {label : 'Non Profit'},
    {label : 'Other'},
];

export const countryOptions = [
    { label: "Afghanistan", value: "Afghanistan" },
    { label: "Albania", value: "Albania" },
    { label: "Algeria", value: "Algeria" },
    { label: "Andorra", value: "Andorra" },
    { label: "Angola", value: "Angola" },
    { label: "Argentina", value: "Argentina" },
    { label: "Armenia", value: "Armenia" },
    { label: "Australia", value: "Australia" },
    { label: "Austria", value: "Austria" },
    { label: "Azerbaijan", value: "Azerbaijan" },
    { label: "Bahamas", value: "Bahamas" },
    { label: "Bahrain", value: "Bahrain" },
    { label: "Bangladesh", value: "Bangladesh" },
    { label: "Barbados", value: "Barbados" },
    { label: "Belarus", value: "Belarus" },
    { label: "Belgium", value: "Belgium" },
    { label: "Belize", value: "Belize" },
    { label: "Benin", value: "Benin" },
    { label: "Bhutan", value: "Bhutan" },
    { label: "Bolivia", value: "Bolivia" },
    { label: "Bosnia and Herzegovina", value: "Bosnia and Herzegovina" },
    { label: "Botswana", value: "Botswana" },
    { label: "Brazil", value: "Brazil" },
    { label: "Brunei", value: "Brunei" },
    { label: "Bulgaria", value: "Bulgaria" },
    { label: "Burkina Faso", value: "Burkina Faso" },
    { label: "Burundi", value: "Burundi" },
    { label: "Cabo Verde", value: "Cabo Verde" },
    { label: "Cambodia", value: "Cambodia" },
    { label: "Cameroon", value: "Cameroon" },
    { label: "Canada", value: "Canada" },
    { label: "Central African Republic", value: "Central African Republic" },
    { label: "Chad", value: "Chad" },
    { label: "Chile", value: "Chile" },
    { label: "China", value: "China" },
    { label: "Colombia", value: "Colombia" },
    { label: "Comoros", value: "Comoros" },
    { label: "Congo (Congo-Brazzaville)", value: "Congo (Congo-Brazzaville)" },
    { label: "Congo (Democratic Republic)", value: "Congo (Democratic Republic)" },
    { label: "Costa Rica", value: "Costa Rica" },
    { label: "Croatia", value: "Croatia" },
    { label: "Cuba", value: "Cuba" },
    { label: "Cyprus", value: "Cyprus" },
    { label: "Czechia (Czech Republic)", value: "Czechia (Czech Republic)" },
    { label: "Denmark", value: "Denmark" },
    { label: "Djibouti", value: "Djibouti" },
    { label: "Dominica", value: "Dominica" },
    { label: "Dominican Republic", value: "Dominican Republic" },
    { label: "Ecuador", value: "Ecuador" },
    { label: "Egypt", value: "Egypt" },
    { label: "El Salvador", value: "El Salvador" },
    { label: "Equatorial Guinea", value: "Equatorial Guinea" },
    { label: "Eritrea", value: "Eritrea" },
    { label: "Estonia", value: "Estonia" },
    { label: "Eswatini (Swaziland)", value: "Eswatini (Swaziland)" },
    { label: "Ethiopia", value: "Ethiopia" },
    { label: "Fiji", value: "Fiji" },
    { label: "Finland", value: "Finland" },
    { label: "France", value: "France" },
    { label: "Gabon", value: "Gabon" },
    { label: "Gambia", value: "Gambia" },
    { label: "Georgia", value: "Georgia" },
    { label: "Germany", value: "Germany" },
    { label: "Ghana", value: "Ghana" },
    { label: "Greece", value: "Greece" },
    { label: "Grenada", value: "Grenada" },
    { label: "Guatemala", value: "Guatemala" },
    { label: "Guinea", value: "Guinea" },
    { label: "Guinea-Bissau", value: "Guinea-Bissau" },
    { label: "Guyana", value: "Guyana" },
    { label: "Haiti", value: "Haiti" },
    { label: "Honduras", value: "Honduras" },
    { label: "Hungary", value: "Hungary" },
    { label: "Iceland", value: "Iceland" },
    { label: "India", value: "India" },
    { label: "Indonesia", value: "Indonesia" },
    { label: "Iran", value: "Iran" },
    { label: "Iraq", value: "Iraq" },
    { label: "Ireland", value: "Ireland" },
    { label: "Israel", value: "Israel" },
    { label: "Italy", value: "Italy" },
    { label: "Jamaica", value: "Jamaica" },
    { label: "Japan", value: "Japan" },
    { label: "Jordan", value: "Jordan" },
    { label: "Kazakhstan", value: "Kazakhstan" },
    { label: "Kenya", value: "Kenya" },
    { label: "Kiribati", value: "Kiribati" },
    { label: "Kuwait", value: "Kuwait" },
    { label: "Kyrgyzstan", value: "Kyrgyzstan" },
    { label: "Laos", value: "Laos" },
    { label: "Latvia", value: "Latvia" },
    { label: "Lebanon", value: "Lebanon" },
    { label: "Lesotho", value: "Lesotho" },
    { label: "Liberia", value: "Liberia" },
    { label: "Libya", value: "Libya" },
    { label: "Liechtenstein", value: "Liechtenstein" },
    { label: "Lithuania", value: "Lithuania" },
    { label: "Luxembourg", value: "Luxembourg" },
    { label: "Madagascar", value: "Madagascar" },
    { label: "Malawi", value: "Malawi" },
    { label: "Malaysia", value: "Malaysia" },
    { label: "Maldives", value: "Maldives" },
    { label: "Mali", value: "Mali" },
    { label: "Malta", value: "Malta" },
    { label: "Marshall Islands", value: "Marshall Islands" },
    { label: "Mauritania", value: "Mauritania" },
    { label: "Mauritius", value: "Mauritius" },
    { label: "Mexico", value: "Mexico" },
    { label: "Micronesia", value: "Micronesia" },
    { label: "Moldova", value: "Moldova" },
    { label: "Monaco", value: "Monaco" },
    { label: "Mongolia", value: "Mongolia" },
    { label: "Montenegro", value: "Montenegro" },
    { label: "Morocco", value: "Morocco" },
    { label: "Mozambique", value: "Mozambique" },
    { label: "Myanmar (Burma)", value: "Myanmar (Burma)" },
    { label: "Namibia", value: "Namibia" },
    { label: "Nauru", value: "Nauru" },
    { label: "Nepal", value: "Nepal" },
    { label: "Netherlands", value: "Netherlands" },
    { label: "New Zealand", value: "New Zealand" },
    { label: "Nicaragua", value: "Nicaragua" },
    { label: "Niger", value: "Niger" },
    { label: "Nigeria", value: "Nigeria" },
    { label: "North Korea", value: "North Korea" },
    { label: "North Macedonia", value: "North Macedonia" },
    { label: "Norway", value: "Norway" },
    { label: "Oman", value: "Oman" },
    { label: "Pakistan", value: "Pakistan" },
    { label: "Palau", value: "Palau" },
    { label: "Palestine State", value: "Palestine State" },
    { label: "Panama", value: "Panama" },
    { label: "Papua New Guinea", value: "Papua New Guinea" },
    { label: "Paraguay", value: "Paraguay" },
    { label: "Peru", value: "Peru" },
    { label: "Philippines", value: "Philippines" },
    { label: "Poland", value: "Poland" },
    { label: "Portugal", value: "Portugal" },
    { label: "Qatar", value: "Qatar" },
    { label: "Romania", value: "Romania" },
    { label: "Russia", value: "Russia" },
    { label: "Rwanda", value: "Rwanda" },
    { label: "Saint Kitts and Nevis", value: "Saint Kitts and Nevis" },
    { label: "Saint Lucia", value: "Saint Lucia" },
    { label: "Saint Vincent and the Grenadines", value: "Saint Vincent and the Grenadines" },
    { label: "Samoa", value: "Samoa" },
    { label: "San Marino", value: "San Marino" },
    { label: "Sao Tome and Principe", value: "Sao Tome and Principe" },
    { label: "Saudi Arabia", value: "Saudi Arabia" },
    { label: "Senegal", value: "Senegal" },
    { label: "Serbia", value: "Serbia" },
    { label: "Seychelles", value: "Seychelles" },
    { label: "Sierra Leone", value: "Sierra Leone" },
    { label: "Singapore", value: "Singapore" },
    { label: "Slovakia", value: "Slovakia" },
    { label: "Slovenia", value: "Slovenia" },
    { label: "Solomon Islands", value: "Solomon Islands" },
    { label: "Somalia", value: "Somalia" },
    { label: "South Africa", value: "South Africa" },
    { label: "South Korea", value: "South Korea" },
    { label: "South Sudan", value: "South Sudan" },
    { label: "Spain", value: "Spain" },
    { label: "Sri Lanka", value: "Sri Lanka" },
    { label: "Sudan", value: "Sudan" },
    { label: "Suriname", value: "Suriname" },
    { label: "Sweden", value: "Sweden" },
    { label: "Switzerland", value: "Switzerland" },
    { label: "Syria", value: "Syria" },
    { label: "Taiwan", value: "Taiwan" },
    { label: "Tajikistan", value: "Tajikistan" },
    { label: "Tanzania", value: "Tanzania" },
    { label: "Thailand", value: "Thailand" },
    { label: "Timor-Leste", value: "Timor-Leste" },
    { label: "Togo", value: "Togo" },
    { label: "Tonga", value: "Tonga" },
    { label: "Trinidad and Tobago", value: "Trinidad and Tobago" },
    { label: "Tunisia", value: "Tunisia" },
    { label: "Turkey", value: "Turkey" },
    { label: "Turkmenistan", value: "Turkmenistan" },
    { label: "Tuvalu", value: "Tuvalu" },
    { label: "Uganda", value: "Uganda" },
    { label: "Ukraine", value: "Ukraine" },
    { label: "United Arab Emirates", value: "United Arab Emirates" },
    { label: "United Kingdom", value: "United Kingdom" },
    { label: "United States of America", value: "United States of America" },
    { label: "Uruguay", value: "Uruguay" },
    { label: "Uzbekistan", value: "Uzbekistan" },
    { label: "Vanuatu", value: "Vanuatu" },
    { label: "Vatican City", value: "Vatican City" },
    { label: "Venezuela", value: "Venezuela" },
    { label: "Vietnam", value: "Vietnam" },
    { label: "Yemen", value: "Yemen" },
    { label: "Zambia", value: "Zambia" },
    { label: "Zimbabwe", value: "Zimbabwe" },
  ];
  

  export const currencyOptions = [
    { label: "USD", value: "USD" },
    { label: "EUR", value: "EUR" },
    { label: "GBP", value: "GBP" },
    { label: "JPY", value: "JPY" },
    { label: "AUD", value: "AUD" },
    { label: "CAD", value: "CAD" },
    { label: "CHF", value: "CHF" },
    { label: "CNY", value: "CNY" },
    { label: "SEK", value: "SEK" },
    { label: "NZD", value: "NZD" },
    { label: "MXN", value: "MXN" },
    { label: "SGD", value: "SGD" },
    { label: "HKD", value: "HKD" },
    { label: "NOK", value: "NOK" },
    { label: "KRW", value: "KRW" },
    { label: "TRY", value: "TRY" },
    { label: "RUB", value: "RUB" },
    { label: "INR", value: "INR" },
    { label: "BRL", value: "BRL" },
    { label: "ZAR", value: "ZAR" },
    { label: "PHP", value: "PHP" },
    { label: "IDR", value: "IDR" },
    { label: "THB", value: "THB" },
    { label: "MYR", value: "MYR" },
    { label: "EGP", value: "EGP" },
    { label: "KES", value: "KES" },
    { label: "NGN", value: "NGN" },
    { label: "PKR", value: "PKR" },
    { label: "VND", value: "VND" },
    { label: "BDT", value: "BDT" },
  ];
  export const languageOptions = [
    { value: 'Afrikaans', label: 'Afrikaans' },
    { value: 'Arabic', label: 'Arabic' },
    { value: 'Azerbaijani', label: 'Azerbaijani' },
    { value: 'Belarusian', label: 'Belarusian' },
    { value: 'Bulgarian', label: 'Bulgarian' },
    { value: 'Bengali', label: 'Bengali' },
    { value: 'Bosnian', label: 'Bosnian' },
    { value: 'Catalan', label: 'Catalan' },
    { value: 'Czech', label: 'Czech' },
    { value: 'Welsh', label: 'Welsh' },
    { value: 'Danish', label: 'Danish' },
    { value: 'German', label: 'German' },
    { value: 'Greek', label: 'Greek' },
    { value: 'English', label: 'English' },
    { value: 'Spanish', label: 'Spanish' },
    { value: 'Estonian', label: 'Estonian' },
    { value: 'Persian', label: 'Persian' },
    { value: 'Finnish', label: 'Finnish' },
    { value: 'French', label: 'French' },
    { value: 'Irish', label: 'Irish' },
    { value: 'Galician', label: 'Galician' },
    { value: 'Gujarati', label: 'Gujarati' },
    { value: 'Hebrew', label: 'Hebrew' },
    { value: 'Hindi', label: 'Hindi' },
    { value: 'Croatian', label: 'Croatian' },
    { value: 'Hungarian', label: 'Hungarian' },
    { value: 'Armenian', label: 'Armenian' },
    { value: 'Indonesian', label: 'Indonesian' },
    { value: 'Icelandic', label: 'Icelandic' },
    { value: 'Italian', label: 'Italian' },
    { value: 'Japanese', label: 'Japanese' },
    { value: 'Georgian', label: 'Georgian' },
    { value: 'Kazakh', label: 'Kazakh' },
    { value: 'Khmer', label: 'Khmer' },
    { value: 'Kannada', label: 'Kannada' },
    { value: 'Korean', label: 'Korean' },
    { value: 'Kyrgyz', label: 'Kyrgyz' },
    { value: 'Lithuanian', label: 'Lithuanian' },
    { value: 'Latvian', label: 'Latvian' },
    { value: 'Macedonian', label: 'Macedonian' },
    { value: 'Malayalam', label: 'Malayalam' },
    { value: 'Mongolian', label: 'Mongolian' },
    { value: 'Marathi', label: 'Marathi' },
    { value: 'Malay', label: 'Malay' },
    { value: 'Burmese', label: 'Burmese' },
    { value: 'Nepali', label: 'Nepali' },
    { value: 'Dutch', label: 'Dutch' },
    { value: 'Norwegian', label: 'Norwegian' },
    { value: 'Punjabi', label: 'Punjabi' },
    { value: 'Polish', label: 'Polish' },
    { value: 'Portuguese', label: 'Portuguese' },
    { value: 'Romanian', label: 'Romanian' },
    { value: 'Russian', label: 'Russian' },
    { value: 'Sinhala', label: 'Sinhala' },
    { value: 'Slovak', label: 'Slovak' },
    { value: 'Slovenian', label: 'Slovenian' },
    { value: 'Albanian', label: 'Albanian' },
    { value: 'Serbian', label: 'Serbian' },
    { value: 'Swedish', label: 'Swedish' },
    { value: 'Swahili', label: 'Swahili' },
    { value: 'Tamil', label: 'Tamil' },
    { value: 'Telugu', label: 'Telugu' },
    { value: 'Thai', label: 'Thai' },
    { value: 'Turkish', label: 'Turkish' },
    { value: 'Ukrainian', label: 'Ukrainian' },
    { value: 'Urdu', label: 'Urdu' },
    { value: 'Uzbek', label: 'Uzbek' },
    { value: 'Vietnamese', label: 'Vietnamese' },
    { value: 'Chinese', label: 'Chinese' },
    { value: 'Zulu', label: 'Zulu' }
];
export const timeZoneOptions = [
    { value: 'Africa/Abidjan', label: 'Africa/Abidjan' },
    { value: 'Africa/Accra', label: 'Africa/Accra' },
    { value: 'Africa/Addis_Ababa', label: 'Africa/Addis_Ababa' },
    { value: 'Africa/Algiers', label: 'Africa/Algiers' },
    { value: 'Africa/Asmara', label: 'Africa/Asmara' },
    { value: 'Africa/Bamako', label: 'Africa/Bamako' },
    { value: 'Africa/Bangui', label: 'Africa/Bangui' },
    { value: 'Africa/Banjul', label: 'Africa/Banjul' },
    { value: 'Africa/Bissau', label: 'Africa/Bissau' },
    { value: 'Africa/Blantyre', label: 'Africa/Blantyre' },
    { value: 'Africa/Brazzaville', label: 'Africa/Brazzaville' },
    { value: 'Africa/Bujumbura', label: 'Africa/Bujumbura' },
    { value: 'Africa/Cairo', label: 'Africa/Cairo' },
    { value: 'Africa/Casablanca', label: 'Africa/Casablanca' },
    { value: 'Africa/Ceuta', label: 'Africa/Ceuta' },
    { value: 'Africa/Conakry', label: 'Africa/Conakry' },
    { value: 'Africa/Dakar', label: 'Africa/Dakar' },
    { value: 'Africa/Dar_es_Salaam', label: 'Africa/Dar_es_Salaam' },
    { value: 'Africa/Djibouti', label: 'Africa/Djibouti' },
    { value: 'Africa/Douala', label: 'Africa/Douala' },
    { value: 'Africa/El_Aaiun', label: 'Africa/El_Aaiun' },
    { value: 'Africa/Freetown', label: 'Africa/Freetown' },
    { value: 'Africa/Gaborone', label: 'Africa/Gaborone' },
    { value: 'Africa/Harare', label: 'Africa/Harare' },
    { value: 'Africa/Johannesburg', label: 'Africa/Johannesburg' },
    { value: 'Africa/Juba', label: 'Africa/Juba' },
    { value: 'Africa/Kampala', label: 'Africa/Kampala' },
    { value: 'Africa/Khartoum', label: 'Africa/Khartoum' },
    { value: 'Africa/Kigali', label: 'Africa/Kigali' },
    { value: 'Africa/Kinshasa', label: 'Africa/Kinshasa' },
    { value: 'Africa/Lagos', label: 'Africa/Lagos' },
    { value: 'Africa/Libreville', label: 'Africa/Libreville' },
    { value: 'Africa/Lome', label: 'Africa/Lome' },
    { value: 'Africa/Luanda', label: 'Africa/Luanda' },
    { value: 'Africa/Lubumbashi', label: 'Africa/Lubumbashi' },
    { value: 'Africa/Lusaka', label: 'Africa/Lusaka' },
    { value: 'Africa/Malabo', label: 'Africa/Malabo' },
    { value: 'Africa/Maputo', label: 'Africa/Maputo' },
    { value: 'Africa/Maseru', label: 'Africa/Maseru' },
    { value: 'Africa/Mbabane', label: 'Africa/Mbabane' },
    { value: 'Africa/Mogadishu', label: 'Africa/Mogadishu' },
    { value: 'Africa/Monrovia', label: 'Africa/Monrovia' },
    { value: 'Africa/Nairobi', label: 'Africa/Nairobi' },
    { value: 'Africa/Ndjamena', label: 'Africa/Ndjamena' },
    { value: 'Africa/Niamey', label: 'Africa/Niamey' },
    { value: 'Africa/Nouakchott', label: 'Africa/Nouakchott' },
    { value: 'Africa/Ouagadougou', label: 'Africa/Ouagadougou' },
    { value: 'Africa/Porto-Novo', label: 'Africa/Porto-Novo' },
    { value: 'Africa/Sao_Tome', label: 'Africa/Sao_Tome' },
    { value: 'Africa/Tripoli', label: 'Africa/Tripoli' },
    { value: 'Africa/Tunis', label: 'Africa/Tunis' },
    { value: 'Africa/Windhoek', label: 'Africa/Windhoek' },
    { value: 'America/Adak', label: 'America/Adak' },
    { value: 'America/Anchorage', label: 'America/Anchorage' },
    { value: 'America/Anguilla', label: 'America/Anguilla' },
    { value: 'America/Antigua', label: 'America/Antigua' },
    { value: 'America/Araguaina', label: 'America/Araguaina' },
    { value: 'America/Argentina/Buenos_Aires', label: 'America/Argentina/Buenos_Aires' },
    { value: 'America/Argentina/Catamarca', label: 'America/Argentina/Catamarca' },
    { value: 'America/Argentina/Cordoba', label: 'America/Argentina/Cordoba' },
    { value: 'America/Argentina/Jujuy', label: 'America/Argentina/Jujuy' },
    { value: 'America/Argentina/La_Rioja', label: 'America/Argentina/La_Rioja' },
    { value: 'America/Argentina/Mendoza', label: 'America/Argentina/Mendoza' },
    { value: 'America/Argentina/Rio_Gallegos', label: 'America/Argentina/Rio_Gallegos' },
    { value: 'America/Argentina/Salta', label: 'America/Argentina/Salta' },
    { value: 'America/Argentina/San_Juan', label: 'America/Argentina/San_Juan' },
    { value: 'America/Argentina/San_Luis', label: 'America/Argentina/San_Luis' },
    { value: 'America/Argentina/Tucuman', label: 'America/Argentina/Tucuman' },
    { value: 'America/Argentina/Ushuaia', label: 'America/Argentina/Ushuaia' },
    { value: 'America/Aruba', label: 'America/Aruba' },
    { value: 'America/Asuncion', label: 'America/Asuncion' },
    { value: 'America/Atikokan', label: 'America/Atikokan' },
    { value: 'America/Bahia', label: 'America/Bahia' },
    { value: 'America/Bahia_Banderas', label: 'America/Bahia_Banderas' },
    { value: 'America/Barbados', label: 'America/Barbados' },
    { value: 'America/Belem', label: 'America/Belem' },
    { value: 'America/Belize', label: 'America/Belize' },
    { value: 'America/Blanc-Sablon', label: 'America/Blanc-Sablon' },
    { value: 'America/Boa_Vista', label: 'America/Boa_Vista' },
    { value: 'America/Bogota', label: 'America/Bogota' },
    { value: 'America/Boise', label: 'America/Boise' },
    { value: 'America/Cambridge_Bay', label: 'America/Cambridge_Bay' },
    { value: 'America/Campo_Grande', label: 'America/Campo_Grande' },
    { value: 'America/Cancun', label: 'America/Cancun' },
    { value: 'America/Caracas', label: 'America/Caracas' },
    { value: 'America/Cayenne', label: 'America/Cayenne' },
    { value: 'America/Cayman', label: 'America/Cayman' },
    { value: 'America/Chicago', label: 'America/Chicago' },
    { value: 'America/Chihuahua', label: 'America/Chihuahua' },
    { value: 'America/Costa_Rica', label: 'America/Costa_Rica' },
    { value: 'America/Creston', label: 'America/Creston' },
    { value: 'America/Cuiaba', label: 'America/Cuiaba' },
    { value: 'America/Curacao', label: 'America/Curacao' },
    { value: 'America/Danmarkshavn', label: 'America/Danmarkshavn' },
    { value: 'America/Dawson', label: 'America/Dawson' },
    { value: 'America/Dawson_Creek', label: 'America/Dawson_Creek' },
    { value: 'America/Denver', label: 'America/Denver' },
    { value: 'America/Detroit', label: 'America/Detroit' },
    { value: 'America/Dominica', label: 'America/Dominica' },
    { value: 'America/Edmonton', label: 'America/Edmonton' },
    { value: 'America/Eirunepe', label: 'America/Eirunepe' },
    { value: 'America/El_Salvador', label: 'America/El_Salvador' },
    { value: 'America/Fort_Nelson', label: 'America/Fort_Nelson' },
    { value: 'America/Fortaleza', label: 'America/Fortaleza' },
    { value: 'America/Glace_Bay', label: 'America/Glace_Bay' },
    { value: 'America/Godthab', label: 'America/Godthab' },
    { value: 'America/Goose_Bay', label: 'America/Goose_Bay' },
    { value: 'America/Grand_Turk', label: 'America/Grand_Turk' },
    { value: 'America/Grenada', label: 'America/Grenada' },
    { value: 'America/Guadeloupe', label: 'America/Guadeloupe' },
    { value: 'America/Guatemala', label: 'America/Guatemala' },
    { value: 'America/Guayaquil', label: 'America/Guayaquil' },
    { value: 'America/Guyana', label: 'America/Guyana' },
    { value: 'America/Halifax', label: 'America/Halifax' },
    { value: 'America/Havana', label: 'America/Havana' },
    { value: 'America/Hermosillo', label: 'America/Hermosillo' },
    { value: 'America/Indiana/Indianapolis', label: 'America/Indiana/Indianapolis' },
    { value: 'America/Indiana/Knox', label: 'America/Indiana/Knox' },
    { value: 'America/Indiana/Marengo', label: 'America/Indiana/Marengo' },
    { value: 'America/Indiana/Petersburg', label: 'America/Indiana/Petersburg' },
    { value: 'America/Indiana/Tell_City', label: 'America/Indiana/Tell_City' },
    { value: 'America/Indiana/Vevay', label: 'America/Indiana/Vevay' },
    { value: 'America/Indiana/Vincennes', label: 'America/Indiana/Vincennes' },
    { value: 'America/Indiana/Winamac', label: 'America/Indiana/Winamac' },
    { value: 'America/Inuvik', label: 'America/Inuvik' },
    { value: 'America/Iqaluit', label: 'America/Iqaluit' },
    { value: 'America/Jamaica', label: 'America/Jamaica' },
    { value: 'America/Juneau', label: 'America/Juneau' },
    { value: 'America/Kentucky/Louisville', label: 'America/Kentucky/Louisville' },
    { value: 'America/Kentucky/Monticello', label: 'America/Kentucky/Monticello' },
    { value: 'America/Kralendijk', label: 'America/Kralendijk' },
    { value: 'America/La_Paz', label: 'America/La_Paz' },
    { value: 'America/Lima', label: 'America/Lima' },
    { value: 'America/Los_Angeles', label: 'America/Los_Angeles' },
    { value: 'America/Lower_Princes', label: 'America/Lower_Princes' },
    { value: 'America/Maceio', label: 'America/Maceio' },
    { value: 'America/Managua', label: 'America/Managua' },
    { value: 'America/Manaus', label: 'America/Manaus' },
    { value: 'America/Marigot', label: 'America/Marigot' },
    { value: 'America/Martinique', label: 'America/Martinique' },
    { value: 'America/Matamoros', label: 'America/Matamoros' },
    { value: 'America/Mazatlan', label: 'America/Mazatlan' },
    { value: 'America/Menominee', label: 'America/Menominee' },
    { value: 'America/Merida', label: 'America/Merida' },
    { value: 'America/Metlakatla', label: 'America/Metlakatla' },
    { value: 'America/Mexico_City', label: 'America/Mexico_City' },
    { value: 'America/Miquelon', label: 'America/Miquelon' },
    { value: 'America/Moncton', label: 'America/Moncton' },
    { value: 'America/Monterrey', label: 'America/Monterrey' },
    { value: 'America/Montevideo', label: 'America/Montevideo' },
    { value: 'America/Montserrat', label: 'America/Montserrat' },
    { value: 'America/Nassau', label: 'America/Nassau' },
    { value: 'America/New_York', label: 'America/New_York' },
    { value: 'America/Nipigon', label: 'America/Nipigon' },
    { value: 'America/Nome', label: 'America/Nome' },
    { value: 'America/Noronha', label: 'America/Noronha' },
    { value: 'America/North_Dakota/Beulah', label: 'America/North_Dakota/Beulah' },
    { value: 'America/North_Dakota/Center', label: 'America/North_Dakota/Center' },
    { value: 'America/North_Dakota/New_Salem', label: 'America/North_Dakota/New_Salem' },
    { value: 'America/Nuuk', label: 'America/Nuuk' },
    { value: 'America/Ojinaga', label: 'America/Ojinaga' },
    { value: 'America/Panama', label: 'America/Panama' },
    { value: 'America/Pangnirtung', label: 'America/Pangnirtung' },
    { value: 'America/Paramaribo', label: 'America/Paramaribo' },
    { value: 'America/Phoenix', label: 'America/Phoenix' },
    { value: 'America/Port-au-Prince', label: 'America/Port-au-Prince' },
    { value: 'America/Port_of_Spain', label: 'America/Port_of_Spain' },
    { value: 'America/Porto_Velho', label: 'America/Porto_Velho' },
    { value: 'America/Puerto_Rico', label: 'America/Puerto_Rico' },
    { value: 'America/Punta_Arenas', label: 'America/Punta_Arenas' },
    { value: 'America/Rainy_River', label: 'America/Rainy_River' },
    { value: 'America/Rankin_Inlet', label: 'America/Rankin_Inlet' },
    { value: 'America/Recife', label: 'America/Recife' },
    { value: 'America/Regina', label: 'America/Regina' },
    { value: 'America/Resolute', label: 'America/Resolute' },
    { value: 'America/Rio_Branco', label: 'America/Rio_Branco' },
    { value: 'America/Santarem', label: 'America/Santarem' },
    { value: 'America/Santiago', label: 'America/Santiago' },
    { value: 'America/Santo_Domingo', label: 'America/Santo_Domingo' },
    { value: 'America/Sao_Paulo', label: 'America/Sao_Paulo' },
    { value: 'America/Scoresbysund', label: 'America/Scoresbysund' },
    { value: 'America/Sitka', label: 'America/Sitka' },
    { value: 'America/St_Barthelemy', label: 'America/St_Barthelemy' },
    { value: 'America/St_Johns', label: 'America/St_Johns' },
    { value: 'America/St_Kitts', label: 'America/St_Kitts' },
    { value: 'America/St_Lucia', label: 'America/St_Lucia' },
    { value: 'America/St_Thomas', label: 'America/St_Thomas' },
    { value: 'America/St_Vincent', label: 'America/St_Vincent' },
    { value: 'America/Swift_Current', label: 'America/Swift_Current' },
    { value: 'America/Tegucigalpa', label: 'America/Tegucigalpa' },
    { value: 'America/Thule', label: 'America/Thule' },
    { value: 'America/Thunder_Bay', label: 'America/Thunder_Bay' },
    { value: 'America/Tijuana', label: 'America/Tijuana' },
    { value: 'America/Toronto', label: 'America/Toronto' },
    { value: 'America/Tortola', label: 'America/Tortola' },
    { value: 'America/Vancouver', label: 'America/Vancouver' },
    { value: 'America/Whitehorse', label: 'America/Whitehorse' },
    { value: 'America/Winnipeg', label: 'America/Winnipeg' },
    { value: 'America/Yakutat', label: 'America/Yakutat' },
    { value: 'America/Yellowknife', label: 'America/Yellowknife' },
    { value: 'Antarctica/Casey', label: 'Antarctica/Casey' },
    { value: 'Antarctica/Davis', label: 'Antarctica/Davis' },
    { value: 'Antarctica/DumontDUrville', label: 'Antarctica/DumontDUrville' },
    { value: 'Antarctica/Macquarie', label: 'Antarctica/Macquarie' },
    { value: 'Antarctica/Mawson', label: 'Antarctica/Mawson' },
    { value: 'Antarctica/McMurdo', label: 'Antarctica/McMurdo' },
    { value: 'Antarctica/Palmer', label: 'Antarctica/Palmer' },
    { value: 'Antarctica/Rothera', label: 'Antarctica/Rothera' },
    { value: 'Antarctica/Syowa', label: 'Antarctica/Syowa' },
    { value: 'Antarctica/Troll', label: 'Antarctica/Troll' },
    { value: 'Antarctica/Vostok', label: 'Antarctica/Vostok' },
    { value: 'Arctic/Longyearbyen', label: 'Arctic/Longyearbyen' },
    { value: 'Asia/Aden', label: 'Asia/Aden' },
    { value: 'Asia/Almaty', label: 'Asia/Almaty' },
    { value: 'Asia/Amman', label: 'Asia/Amman' },
    { value: 'Asia/Anadyr', label: 'Asia/Anadyr' },
    { value: 'Asia/Aqtau', label: 'Asia/Aqtau' },
    { value: 'Asia/Aqtobe', label: 'Asia/Aqtobe' },
    { value: 'Asia/Ashgabat', label: 'Asia/Ashgabat' },
    { value: 'Asia/Atyrau', label: 'Asia/Atyrau' },
    { value: 'Asia/Baghdad', label: 'Asia/Baghdad' },
    { value: 'Asia/Bahrain', label: 'Asia/Bahrain' },
    { value: 'Asia/Baku', label: 'Asia/Baku' },
    { value: 'Asia/Bangkok', label: 'Asia/Bangkok' },
    { value: 'Asia/Barnaul', label: 'Asia/Barnaul' },
    { value: 'Asia/Beirut', label: 'Asia/Beirut' },
    { value: 'Asia/Bishkek', label: 'Asia/Bishkek' },
    { value: 'Asia/Brunei', label: 'Asia/Brunei' },
    { value: 'Asia/Chita', label: 'Asia/Chita' },
    { value: 'Asia/Choibalsan', label: 'Asia/Choibalsan' },
    { value: 'Asia/Colombo', label: 'Asia/Colombo' },
    { value: 'Asia/Damascus', label: 'Asia/Damascus' },
    { value: 'Asia/Dhaka', label: 'Asia/Dhaka' },
    { value: 'Asia/Dili', label: 'Asia/Dili' },
    { value: 'Asia/Dubai', label: 'Asia/Dubai' },
    { value: 'Asia/Dushanbe', label: 'Asia/Dushanbe' },
    { value: 'Asia/Famagusta', label: 'Asia/Famagusta' },
    { value: 'Asia/Gaza', label: 'Asia/Gaza' },
    { value: 'Asia/Hebron', label: 'Asia/Hebron' },
    { value: 'Asia/Ho_Chi_Minh', label: 'Asia/Ho_Chi_Minh' },
    { value: 'Asia/Hong_Kong', label: 'Asia/Hong_Kong' },
    { value: 'Asia/Hovd', label: 'Asia/Hovd' },
    { value: 'Asia/Irkutsk', label: 'Asia/Irkutsk' },
    { value: 'Asia/Jakarta', label: 'Asia/Jakarta' },
    { value: 'Asia/Jayapura', label: 'Asia/Jayapura' },
    { value: 'Asia/Jerusalem', label: 'Asia/Jerusalem' },
    { value: 'Asia/Kabul', label: 'Asia/Kabul' },
    { value: 'Asia/Kamchatka', label: 'Asia/Kamchatka' },
    { value: 'Asia/Karachi', label: 'Asia/Karachi' },
    { value: 'Asia/Kathmandu', label: 'Asia/Kathmandu' },
    { value: 'Asia/Khandyga', label: 'Asia/Khandyga' },
    { value: 'Asia/Kolkata', label: 'Asia/Kolkata' },
    { value: 'Asia/Krasnoyarsk', label: 'Asia/Krasnoyarsk' },
    { value: 'Asia/Kuala_Lumpur', label: 'Asia/Kuala_Lumpur' },
    { value: 'Asia/Kuching', label: 'Asia/Kuching' },
    { value: 'Asia/Kuwait', label: 'Asia/Kuwait' },
    { value: 'Asia/Macau', label: 'Asia/Macau' },
    { value: 'Asia/Magadan', label: 'Asia/Magadan' },
    { value: 'Asia/Makassar', label: 'Asia/Makassar' },
    { value: 'Asia/Manila', label: 'Asia/Manila' },
    { value: 'Asia/Muscat', label: 'Asia/Muscat' },
    { value: 'Asia/Nicosia', label: 'Asia/Nicosia' },
    { value: 'Asia/Novokuznetsk', label: 'Asia/Novokuznetsk' },
    { value: 'Asia/Novosibirsk', label: 'Asia/Novosibirsk' },
    { value: 'Asia/Omsk', label: 'Asia/Omsk' },
    { value: 'Asia/Oral', label: 'Asia/Oral' },
    { value: 'Asia/Phnom_Penh', label: 'Asia/Phnom_Penh' },
    { value: 'Asia/Pontianak', label: 'Asia/Pontianak' },
    { value: 'Asia/Pyongyang', label: 'Asia/Pyongyang' },
    { value: 'Asia/Qatar', label: 'Asia/Qatar' },
    { value: 'Asia/Qostanay', label: 'Asia/Qostanay' },
    { value: 'Asia/Qyzylorda', label: 'Asia/Qyzylorda' },
    { value: 'Asia/Riyadh', label: 'Asia/Riyadh' },
    { value: 'Asia/Sakhalin', label: 'Asia/Sakhalin' },
    { value: 'Asia/Samarkand', label: 'Asia/Samarkand' },
    { value: 'Asia/Seoul', label: 'Asia/Seoul' },
    { value: 'Asia/Shanghai', label: 'Asia/Shanghai' },
    { value: 'Asia/Singapore', label: 'Asia/Singapore' },
    { value: 'Asia/Srednekolymsk', label: 'Asia/Srednekolymsk' },
    { value: 'Asia/Taipei', label: 'Asia/Taipei' },
    { value: 'Asia/Tashkent', label: 'Asia/Tashkent' },
    { value: 'Asia/Tbilisi', label: 'Asia/Tbilisi' },
    { value: 'Asia/Tehran', label: 'Asia/Tehran' },
    { value: 'Asia/Thimphu', label: 'Asia/Thimphu' },
    { value: 'Asia/Tokyo', label: 'Asia/Tokyo' },
    { value: 'Asia/Tomsk', label: 'Asia/Tomsk' },
    { value: 'Asia/Ulaanbaatar', label: 'Asia/Ulaanbaatar' },
    { value: 'Asia/Urumqi', label: 'Asia/Urumqi' },
    { value: 'Asia/Ust-Nera', label: 'Asia/Ust-Nera' },
    { value: 'Asia/Vientiane', label: 'Asia/Vientiane' },
    { value: 'Asia/Vladivostok', label: 'Asia/Vladivostok' },
    { value: 'Asia/Yakutsk', label: 'Asia/Yakutsk' },
    { value: 'Asia/Yangon', label: 'Asia/Yangon' },
    { value: 'Asia/Yekaterinburg', label: 'Asia/Yekaterinburg' },
    { value: 'Asia/Yerevan', label: 'Asia/Yerevan' },
    { value: 'Atlantic/Azores', label: 'Atlantic/Azores' },
    { value: 'Atlantic/Bermuda', label: 'Atlantic/Bermuda' },
    { value: 'Atlantic/Canary', label: 'Atlantic/Canary' }
]

  